# Generated by Django 4.2.7 on 2026-03-01 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rooms.models.generate_room_code, max_length=10, unique=True)),
                ('host_session_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('current_video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('current_video_title', models.CharField(blank=True, max_length=300, null=True)),
                ('current_video_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('current_thumbnail', models.URLField(blank=True, null=True)),
                ('is_playing', models.BooleanField(default=False)),
                ('progress_ms', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room')),
            ],
            options={
                'unique_together': {('room', 'session_key')},
            },
        ),
    ]
